from __future__ import annotations

import importlib.util
from pathlib import Path


_CONFIG_PATH = Path(__file__).resolve().parents[2] / "config.py"
_SPEC = importlib.util.spec_from_file_location("graph_agent_root_config", _CONFIG_PATH)

if _SPEC is None or _SPEC.loader is None:
    raise RuntimeError(f"Unable to load graph agent config from '{_CONFIG_PATH}'.")

_MODULE = importlib.util.module_from_spec(_SPEC)
_SPEC.loader.exec_module(_MODULE)

GRAPH_AGENT_NAME = _MODULE.GRAPH_AGENT_NAME
GRAPH_AGENT_VERSION = _MODULE.GRAPH_AGENT_VERSION
DEFAULT_GRAPH_ID = _MODULE.DEFAULT_GRAPH_ID
DEFAULT_RUN_MAX_STEPS = _MODULE.DEFAULT_RUN_MAX_STEPS
DEFAULT_MAX_VISITS_PER_NODE = _MODULE.DEFAULT_MAX_VISITS_PER_NODE
DEFAULT_MAX_REPAIR_ATTEMPTS = _MODULE.DEFAULT_MAX_REPAIR_ATTEMPTS
DEFAULT_MODEL_PROVIDER = _MODULE.DEFAULT_MODEL_PROVIDER
DEFAULT_MODEL_TIMEOUT_SECONDS = _MODULE.DEFAULT_MODEL_TIMEOUT_SECONDS
DEFAULT_MODEL_TEMPERATURE = _MODULE.DEFAULT_MODEL_TEMPERATURE
DEFAULT_UI_STREAM_MODE = _MODULE.DEFAULT_UI_STREAM_MODE
SCHEMA_PROPOSAL_PROMPT = _MODULE.SCHEMA_PROPOSAL_PROMPT
SCHEMA_REPAIR_PROMPT = _MODULE.SCHEMA_REPAIR_PROMPT
FINAL_RESPONSE_PROMPT = _MODULE.FINAL_RESPONSE_PROMPT
