import type { GraphDefinition, GraphNode } from "./types";
import { getNodeInstanceLabel } from "./nodeInstanceLabels";

const CONTEXT_BUILDER_DATA_DISPLAY_PROVIDER_ID = "core.data_display";

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function uniqueStrings(values: string[]): string[] {
  return [...new Set(values.filter((value) => value.trim().length > 0))];
}

/** Normalizes placeholder tokens to match runtime / backend slug rules. */
export function slugifyContextBuilderPlaceholder(value: string, fallback: string): string {
  const normalize = (input: string) => input.trim().toLowerCase().replace(/[^a-z0-9_]+/g, "_").replace(/^_+|_+$/g, "");
  const normalized = normalize(value);
  const fallbackValue = normalize(fallback) || "source";
  const resolved = normalized || fallbackValue;
  return /^[0-9]/.test(resolved) ? `source_${resolved}` : resolved;
}

function getIncomingContextBuilderSourceNodes(graph: GraphDefinition, nodeId: string): GraphNode[] {
  const incomingEdges = graph.edges.filter((edge) => edge.target_id === nodeId);
  const bindingSourceIds = incomingEdges.filter((edge) => edge.kind === "binding").map((edge) => edge.source_id);
  const sourceIds = uniqueStrings([...bindingSourceIds, ...incomingEdges.map((edge) => edge.source_id)]);
  return sourceIds
    .map((sourceId) => graph.nodes.find((candidate) => candidate.id === sourceId) ?? null)
    .filter((n): n is GraphNode => n !== null);
}

export type ContextBuilderBindingRow = {
  sourceNodeId: string;
  sourceLabel: string;
  placeholder: string;
  binding: Record<string, unknown>;
  autoGenerated: boolean;
};

/**
 * Resolved bindings for a context builder node — matches runtime merge order:
 * configured input_bindings, then standard edges from data_display (when any binding is configured),
 * then any remaining incoming sources.
 */
export function getContextBuilderBindings(node: GraphNode, graph: GraphDefinition): ContextBuilderBindingRow[] {
  const incomingSources = getIncomingContextBuilderSourceNodes(graph, node.id);
  const incomingSourceIds = new Set(incomingSources.map((source) => source.id));
  const sourceById = new Map(incomingSources.map((source) => [source.id, source] as const));
  const rawBindings = Array.isArray(node.config.input_bindings) ? node.config.input_bindings : [];
  const configuredBindings: ContextBuilderBindingRow[] = [];

  for (const entry of rawBindings) {
    if (!isRecord(entry)) {
      continue;
    }
    const sourceNodeId = String(entry.source_node_id ?? entry.source ?? "").trim();
    if (!sourceNodeId || !incomingSourceIds.has(sourceNodeId)) {
      continue;
    }
    const sourceNode = sourceById.get(sourceNodeId);
    const placeholder = slugifyContextBuilderPlaceholder(
      String(entry.placeholder ?? ""),
      sourceNode ? getNodeInstanceLabel(graph, sourceNode) : sourceNodeId,
    );
    configuredBindings.push({
      sourceNodeId,
      sourceLabel: sourceNode ? getNodeInstanceLabel(graph, sourceNode) : sourceNodeId,
      placeholder,
      binding: isRecord(entry.binding) ? entry.binding : { type: "latest_payload", source: sourceNodeId },
      autoGenerated: false,
    });
  }

  const configuredSourceIds = new Set(configuredBindings.map((binding) => binding.sourceNodeId));
  const hasExplicitInputBindings = configuredBindings.length > 0;
  const standardDisplayBindings: ContextBuilderBindingRow[] = [];

  if (hasExplicitInputBindings) {
    for (const edge of graph.edges) {
      if (edge.target_id !== node.id || edge.kind !== "standard") {
        continue;
      }
      const sid = edge.source_id;
      if (configuredSourceIds.has(sid)) {
        continue;
      }
      const sourceNode = graph.nodes.find((n) => n.id === sid);
      if (!sourceNode || sourceNode.provider_id !== CONTEXT_BUILDER_DATA_DISPLAY_PROVIDER_ID) {
        continue;
      }
      standardDisplayBindings.push({
        sourceNodeId: sid,
        sourceLabel: getNodeInstanceLabel(graph, sourceNode),
        placeholder: slugifyContextBuilderPlaceholder(getNodeInstanceLabel(graph, sourceNode), sid),
        binding: { type: "latest_payload", source: sid },
        autoGenerated: true,
      });
      configuredSourceIds.add(sid);
    }
  }

  const autoDerivedBindings = incomingSources
    .filter((sourceNode) => !configuredSourceIds.has(sourceNode.id))
    .map((sourceNode, index) => ({
      sourceNodeId: sourceNode.id,
      sourceLabel: getNodeInstanceLabel(graph, sourceNode),
      placeholder: slugifyContextBuilderPlaceholder(getNodeInstanceLabel(graph, sourceNode), `source_${index + 1}`),
      binding: { type: "latest_payload", source: sourceNode.id },
      autoGenerated: true,
    }));

  return [...configuredBindings, ...standardDisplayBindings, ...autoDerivedBindings];
}
